[profile.default]
src = "src"
out = "out"
libs = ["lib"]
  
remappings=[
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@vittominacori/erc1363/contracts/=lib/erc1363-payable-token/contracts/']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
